_ZNotice_p2c: Declare type for charset
This is needed since _ZCharsets isn’t a real type.  Fixes this build
error:

_zephyr.c: In function ‘__pyx_f_7_zephyr__ZNotice_p2c’:
_zephyr.c:2913:19: error: storage size of ‘__pyx_v_charset’ isn’t known
   enum _ZCharsets __pyx_v_charset;
                   ^~~~~~~~~~~~~~~

Signed-off-by: Anders Kaseorg <andersk@mit.edu>